services: 
    postgresql:
        image: postgres:17
        #restart: always
        env_file:
            - ./postgresql/.env.dev
        volumes: 
            - postgresql-data:/var/lib/postgresql/data
        networks:
            - odoo-network

    odoo:
        build: ./odoo
        #restart: always
        depends_on:
            - postgresql
        ports:
            - 9069:8069
        volumes: 
            - odoo-data:/var/lib/odoo/
            - ./odoo/extra-addons/:/mnt/extra-addons/
            - ./odoo/custom-addons/:/mnt/custom-addons/
            - ./odoo/oca-addons/:/mnt/oca-addons/
            - ./odoo/l10n-peru/:/mnt/l10n-peru/
            - ./odoo/adhoc/:/mnt/adhoc/
            - ./odoo/odoo.conf:/etc/odoo/odoo.conf
        env_file:
            - ./odoo/.env.dev
        networks:
            - odoo-network
volumes: 
    postgresql-data:
    odoo-data:

networks:
    odoo-network:
        driver: bridge    
