[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
    sniStrict = true

[tls]
  [[tls.certificates]]
    certFile = "/etc/traefik/certs/local-cert.pem"
    keyFile = "/etc/traefik/certs/local-key.pem"
