[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true
  insecure = true

[certificatesResolvers.myresolver.acme]
  email = "tu@email.com"
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.myresolver.acme.tlsChallenge]

[providers.docker]
  watch = true
  network = "odoo-network"

[providers.file]
  filename = "/etc/traefik/dynamic_conf.toml"
